name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - Windows
        py:
          - "3.11"
          - "3.10"
          - "3.9"
    steps:
      - uses: actions/checkout@v3
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: 1.5.1
      - name: Install dependencies
        run: |
          poetry update
          poetry run pip install --upgrade setuptools
          poetry install
      - name: Run tests
        run: poetry run pytest
